### ISSUE TITLE
Image scaling doesn't seem to work on mobile browser

### ISSUE THREAD

**Issue by glennsarti** [bradygaster-zz/downr#7]
I was reading the Hello 2017 blog post on bradygaster.com (http://www.bradygaster.com/posts/hello-2017) (which is great btw) on my mobile (Android running chrome browser), but the images weren't scaled down so I had to do a lot of furious scrolling.  However they work fine on Chrome on a desktop OS (Win 10).

It rendered like this:

```
text
text
text
+----------------------------------------...
|  MASSIVE PICTURE
|
|
|
|
|
|
|
|
|
|
|
|
|
+----------------------------------------...
text
text
```

**Comment by bradygaster-zz** [comment]
Thanks for sending this in. Would you happen to have a screen shot handy so i could see? Thanks!

**Comment by glennsarti** [comment]
That picture is the top left-hand segment of the whole image

![screenshot_2017-01-16-21-20-12](https://cloud.githubusercontent.com/assets/5819622/22008659/f564a410-dc31-11e6-874d-6d663c868895.png)

**Comment by BenjaminAbt** [comment]
This issue is caused by the Markdown img renderer. There is a width="100%" missing.

**Comment by glennsarti** [comment]
Did you want to ping me on GitHub to test it's fixed once it's deployed?
